### ISSUE TITLE
Pytorch version 0.4 / 0.4.1?

### ISSUE THREAD

**Issue by expectopatronum** [cemanil/LNets#1]
Hi,
your README states "All the experiments were performed using PyTorch version 0.4" which made me think you used 0.4.0 but I think it should be 0.4.1 since for example `from torch.utils.data import Subset, DataLoader` causes an error using torch==0.4.0. `torch.utils.data.dataset.Subset` was moved to `torch.utils.data.Subset` in [v0.4.1](https://github.com/pytorch/pytorch/tree/v0.4.1). It's working now for me but it might save others time if you could clarify this.
Thanks and best regards,
Verena

**Comment by cemanil** [comment]
Thank you for pointing this out. Updated the README accordingly.
