### ISSUE TITLE
Correct usage of distrib1.dim

### ISSUE THREAD

**Issue by expectopatronum** [cemanil/LNets#2]
Hi again,

I am currently trying to run `python ./lnets/tasks/dualnets/mains/train_dual.py ./lnets/tasks/dualnets/configs/high_dimensional_cone_experiment.json`. The only thing I changed in the config are: `"save_best": true`, `"cuda": true` and `"visualize": true`.

Since this did not create any visualizations I looked into the code and was confused by [this function](https://github.com/cemanil/LNets/blob/master/lnets/utils/saving_and_loading.py#L97):

```
def save_1_or_2_dim_dualnet_visualizations(model, dim, figures_dir, config, epoch=None, loss=None,
                                           after_training=False):
    if not after_training:
        if dim == 2:
            save_2d_dualnet_visualizations(model, figures_dir, config, epoch, loss)
        if dim == 1:
            save_1d_dualnet_visualizations(model, figures_dir, config, epoch, loss)
    else:
        if config.distrib1.dim == 2:
            save_2d_dualnet_visualizations(model, figures_dir, config, after_training=True)
        if config.distrib1.dim == 1:
            save_1d_dualnet_visualizations(model, figures_dir, config, after_training=True)
```

There is `dim` and `config.distrib1.dim`. At first I thought that the call to `save_1_or_2_dim_dualnet_visualizations` in train_dual.py was wrong and one should pass 1 or 2 instead of `config.distrib1.dim`. After trying this, I realized that actually `dim` and `config.distrib1.dim` should be the same and this is passed redundantly.
I assume plotting is only possible for 1D and 2D distributions (I actually think this was mentioned somewhere in the paper but I don't remember where)?  (This confusion might sound stupid, to clarify: I thought that there was two types of plots - 1D and 2D - to visualize higher dimensional distributions or some of their metrics)

If I am correct and `dim` is always the same as `config.distrib1.dim` and `config` is passed anyways I can fix this and create a pull request.

Best regards
Verena

**Comment by cemanil** [comment]
Yes - since we're already passing the config as an argument, we don't need to pass 'dim' again as a function argument. This was mainly for quick readability, but it seems it is more confusing than is helpful. Would be happy to merge a pull request fixing this. 

Also, as you said, plotting is also possible for 1D and 2D distributions (above that is impossible to plot exactly). It would be interesting to support visualizing 3D slices of high dimensional distributions in a future improvement. 

Thank you.

**Comment by cemanil** [comment]
Merged the pull request - thanks.
